### ISSUE TITLE
Fallo al ejecutar el build.sh dentro de agora

### ISSUE THREAD

**Issue by Espinosa13** [EGCPractica/agora-dev-box#3]
Al ejecutar el build.sh dentro de la máquina agora da fallo relacionado con el grunt, en la imagen se puede observar el fallo concreto.

![photo24787609636158901](https://cloud.githubusercontent.com/assets/14893494/21752539/72d0d530-d5da-11e6-8b4d-84047412b771.jpg)

**Comment by Pablo17p** [comment]
Grunt-cli no está funcionando de manera correcta dentro de la máquina de ágora.

Esto se soluciona desinstalándolo e instalándolo de nuevo.

Para desinstalarlo ejecuta el siguiente comando:
**npm remove -g grunt grunt-cli**

Una vez lo hayas desinstalado, lo instalas con el siguiente comando:
**npm install -g grunt grunt-cli**
